### ISSUE TITLE
Add josephus Problem

### ISSUE THREAD

**Issue by Ambareen09** [Hacktoberfestrepo/hacktoberfest2021#156]
I'd like to add this algorithm in cpp.

**Comment by harsh6975** [comment]
Josephus Problem is a tricker recursive problem. I will explain the intuition behind the code and how we can develop a solution in c++.
M open to collaboration.
Would you mind assigning me?
Thanks.

**Comment by safalta15** [comment]
assign me this issue. i will neatly write

**Comment by aditikhatri201** [comment]
Please assign me this issue. I want to contribute to this problem.
